apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: demo
            operator: In
            values:
            - node-affinity           
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
