apiVersion: v1 
kind: Pod 
metadata: 
  name: pod-affinity
  labels: 
    name: pod-affinity
spec:
  containers: 
  - name: nginx-pod-affinity
    image: nginx 
    ports:
    - containerPort: 80 
--- 
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-affinity
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx-with-pod-affinity
    image: nginx 
